org.gradle.jvmargs=-Xmx3G
org.gradle.java.home=C:/Program Files/Eclipse Adoptium/jdk-25.0.4.7-hotspot

# Mod Properties
mod_version = 4.3.0
maven_group = com.wildfiregender.main
archives_base_name = LFGM

# Minecraft / Forge Properties
mc_version = 1.12.2
forge_version = 14.23.5.2860
mcp_mappings_channel = stable
mcp_mappings_version = 39